site_name: Zanata Jenkins Plugin
docs_dir: docs
repo_name: GitHub
repo_url: https://github.com/jenkinsci/zanata-plugin
# site_favicon: favicon.ico
theme: readthedocs
# theme_dir: For custom themes

pages:
- Home: 'index.md'
- Release notes: 'release-notes.md'
# Getting started
- Getting Started:
  - Installation: 'installation.md'
  - Configuration:
    - Zanata Sync Build Step: 'configuration/zanata-sync.md'
    - Install Zanata CLI: 'configuration/install-cli.md'
    - Post Build: 'configuration/post-build.md'
